---
- hosts: all  

  tasks:
  - name: Modify soft nofile limits for wildcard domain 
    pam_limits:
      domain: "*"
      limit_type: soft 
      limit_item: nofile
      value: "65536"

  - name: Modify soft nofile limits for wildcard domain
    pam_limits:
      domain: "*"
      limit_type: hard
      limit_item: nofile
      value: "65536"
