#!/bin/bash

#VARIVEL QUE RECEBE O IP
IP=$1
#VARIAVEL QUE RECEBE A PORTA
PORT=$2
#VARIAVEL DE TIMEOUT, NOTE QUE O TEMPO AQUI E SEGUNDOS ENTRETANTO O SCRIPT VAI IMPRIMIR NO FINAL EM MILISSEGUNDOs
TIMEOUT=3

#COMEÇA A CONTAGEM DE TEMPO
DATA_INICIO=`date +"%H%M%S%3N"`
#EXECUTA O COMADO PARA SABER O STATUS DA PORTA
TESTE_IP_PORTA=`nc -zv -w $TIMEOUT $IP $PORT 2>&1`
#FINALIZA A CONTAGEM DE TEMPO
DATA_FIM=`date +"%H%M%S%3N"`


#VALIDA SE A PORTA ESTA EM PE, OBSERVER QUAL NC QUE ESTA INSTALADO NO CASO 'Connected' E A REPOSTA QUE ELE QUANDO HA CONEXAO.
STATUS=$(echo "$TESTE_IP_PORTA" | grep -vi VERSION | head -1 | grep -i Connected | wc -l)


#TRAZ A MENSAGEM DOS STATUS DO TESTE
DESCRICAO_STATUS=$(echo "$TESTE_IP_PORTA" | grep -vi VERSION | head -1 )



#FUNCAO VERIFICA TEMPO DE QUE LEVOU PARA EXECUTAR O COMANDO NC
TEMPO_RESPOSTA=`expr $DATA_FIM - $DATA_INICIO`


echo "############# INICIO DO SCRIPT ##############"
echo ""
echo "TEMPO QUE LEVOU PARA EXECUTAR A VERIFICACAO EM MILISSIGUNDO, POR PADRAO O SCRIPT DA TIMEOUT COM 3000 MILISSEGUNDOS."
echo "$TEMPO_RESPOSTA"
echo ""
echo ""
echo "CASO O RESULTADO SEJA 1 SIGNIFICA QUE ELE CONSEGUIU CONEXAO"
echo "$STATUS"
echo ""
echo ""
echo "STRING DO STATUS DA CONEXAO"
echo "$DESCRICAO_STATUS"
echo ""
echo "############## FIM DO SCRIPT ###############"

